vim.cmd.colorscheme "catppuccin"
require("config.options")
require("plugins.packer")
require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.lsp")
require("plugins.bufferline")
require("plugins.comment")
require("plugins.telescope")
require("plugins.treesitter")
